[project]
channels = ["nvidia", "conda-forge"]
name = "puffer_pixi"
platforms = ["linux-64"]

[system-requirements]
cuda = "12.8"

[activation]
scripts = ["venv_setup.sh"]

[dependencies]
python = ">=3.12,<3.13"
pip = ">=25.2,<26"
setuptools = ">=80.9.0,<81"
wheel = ">=0.45.1,<0.46"

# pufferlib build deps
cython = ">=3.1.2,<4"
cuda-toolkit = "==12.8"
numpy = "<2"

[pypi-options]
no-build-isolation = ["pufferlib"]

[pypi-dependencies]
torch = { version = "==2.8.0", index = "https://download.pytorch.org/whl/cu128" }
torchvision = { index = "https://download.pytorch.org/whl/cu128" }
torchaudio = { index = "https://download.pytorch.org/whl/cu128" }
jax = { version = "==0.7.0", extras = ["cuda12-local"] }
pufferlib = { version = ">=3.0.0", extras = ["cuda12-local"] }

[tasks]
test_torch = "python -c 'import torch; print(torch.cuda.is_available())'"
test_jax = "python -c 'import jax; print(jax.devices())'"
puffer = "python -m pufferlib.pufferl"