[project]
channels = ["nvidia", "conda-forge"]
name = "puffer_pixi"
platforms = ["linux-64"]

[activation.env]
CUDA_HOME = "$CONDA_PREFIX"

[system-requirements]
cuda = "12.6"

[dependencies]
python = ">=3.12,<3.13"
pip = "*"
setuptools = "*"
wheel = "*"

# dev-related
git = "*"
ruff = "*"

# CUDA
cuda-version = "12.6.*"
cuda-toolkit = "==12.6.3"

# pufferlib build deps
cython = "*"
numpy = "<2"

[pypi-options]
no-build-isolation = ["pufferlib"]

[pypi-dependencies]
torch = { index = "https://download.pytorch.org/whl/cu126" }
torchvision = { index = "https://download.pytorch.org/whl/cu126" }
torchaudio = { index = "https://download.pytorch.org/whl/cu126" }
jax = { extras = ["cuda12"] }
pufferlib = { version = ">=3.0.0" }

[tasks]
test_torch = "python -c 'import torch; print(torch.cuda.is_available())'"
test_jax = "python test_jax.py"
test_puffer = "python -m pufferlib.pufferl train puffer_breakout --vec.num-envs 4"
reset_puffer = "pip uninstall -y pufferlib; pip install pufferlib --no-build-isolation"
puffer = "python -m pufferlib.pufferl"
